global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 30s
  external_labels:
    monitor: 'blackhole-monitor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 60s
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: 'cadvisor'
