services:

  setup:
    container_name: setup
    build:
      context: ./setup
      dockerfile: Dockerfile
    volumes:
      - ./setup:/setup
    env_file:
      - .env
    restart: on-failure
    init: true
    profiles:
      - setup
    networks:
      - blackholejs

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    restart: on-failure
    # environment:
    #   - GATEWAY_API=http://localhost:6969
    networks:
      - blackholejs

volumes:
  logs_data_nginx:
  logs_data_vector:

networks:
  blackholejs:
    name: blackholejs
    driver: bridge