services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

networks:
  blackholejs:
    name: blackholejs
    driver: bridge