services:

  redis:
    container_name: redis-hole
    build:
      context: ./infra/dockerfiles
      dockerfile: Dockerfile.rd
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

  postgres_db:
    container_name: postgres_db
    build:
      context: ./infra/dockerfiles
      dockerfile: Dockerfile.pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

  pgadmin:
    container_name: pgadmin
    build:
      context: ./infra/dockerfiles
      dockerfile: Dockerfile.pga
    env_file:
      - .env
    ports:
      - 8087:8087
    networks:
      - blackholejs

#https://betterstack.com/community/guides/logging/how-to-view-and-configure-nginx-access-and-error-logs/#step-4-structuring-nginx-access-logs
  nginx:
    container_name: nginx
    build:
      context: ./infra/dockerfiles
      dockerfile: Dockerfile.ng
    ports:
      - "6969:80"
    volumes:
      - ./infra/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/config/502.html:/etc/nginx/conf.d/502.html:ro
      - logs_data_nginx:/var/log/nginx:rw
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

  kafka:
    build:
      context: ./infra/dockerfiles
      dockerfile: Dockerfile.kf
    container_name: kafka
    ports:
      - "9092:9092"
    restart: on-failure
    networks:
      - blackholejs

  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./infra/gateway/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./infra/gateway:/gateway
      - /gateway/node_modules
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

volumes:
  redis_data:
  postgres_data:
  kafka_data:
  logs_data_nginx:
  
networks:
  blackholejs:
    external: true