services:

  redis:
    container_name: redis-hole
    image: redis:8.0-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      # - ./infra/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs



  postgres_db:
    container_name: postgres_db
    image: postgres:17.5-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./infra/config/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      # - ./infra/config/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs



#https://betterstack.com/community/guides/logging/how-to-view-and-configure-nginx-access-and-error-logs/#step-4-structuring-nginx-access-logs
  nginx:
    container_name: nginx
    image: nginx:1.28-alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    volumes:
      # - ./infra/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./infra/config/proxy_params:/etc/nginx/proxy_params:ro
      - ./infra/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/logs/nginx:/var/log/nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    env_file:
      - .env
    restart: on-failure
    networks:
      - blackholejs

  # nginx_proxy_manager:
  #   container_name: nginx_proxy_manager
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #   volumes:
  #     - ./infra/data:/data
  #   env_file:
  #     - .env
  #   networks:
  #     - blackholejs


  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./infra/gateway/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./infra/gateway:/gateway
      - /gateway/node_modules
    env_file:
      - .env
    restart: on-failure
    # depends_on:
    #   - nginx
    #   - postgres_db
    #   - redis
    #   - auth
    #   - chat
    #   - dashboard
    #   - game
    networks:
      - blackholejs

volumes:
  redis_data:
  postgres_data:

networks:
  blackholejs:
    external: true