## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

# filebeat.config:
#   modules:
#     path: ${path.config}/modules.d/*.yml
#     reload.enabled: false

# Input configuration for container logs using filestream instead of log
filebeat.inputs:
- type: filestream
  enabled: true
  id: container-logs
  paths:
    - /var/lib/docker/containers/*/*.log
  parsers:
    - container: ~
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

# Processor configuration
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata:
      host: ""
  - add_fields:
      target: ""
      fields:
        source: "container_logs"

# Output configuration - send to Logstash
output.logstash:
  hosts: ["logstash:5044"]
  
# Disable direct Elasticsearch output
# output.elasticsearch:
#   hosts: [ http://elasticsearch:9200 ]
#   username: filebeat_internal
#   password: ${FILEBEAT_INTERNAL_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/docs/reference/beats/filebeat/http-endpoint
#

http:
  enabled: true
  host: 0.0.0.0
  port: 5066

# monitoring configuration
# https://www.elastic.co/docs/reference/beats/filebeat/monitoring
monitoring:
  enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644