global:
  scrape_interval: 60s
  evaluation_interval: 30s
  scrape_timeout: 60s
  external_labels:
    monitor: 'blackhole-monitor'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: 60s
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: 'cadvisor'

  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: kafka_exporter
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: nginx_exporter
    static_configs:
      - targets: ['nginx_exporter:9113']