name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push auth service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-auth:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push chat service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/chat
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-chat:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push game service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/game
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-game:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push dash service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/dash
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-dash:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push redis
        uses: docker/build-push-action@v4
        with:
          context: ./infra/redis
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-redis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: ./infra/postgres
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-postgres:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push kafka
        uses: docker/build-push-action@v4
        with:
          context: ./infra/kafka
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-kafka:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push pgadmin
        uses: docker/build-push-action@v4
        with:
          context: ./infra/pgadmin
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-pgadmin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push nginx
        uses: docker/build-push-action@v4
        with:
          context: ./infra/nginx
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push prometheus
        uses: docker/build-push-action@v4
        with:
          context: ./metrics/prometheus
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-prometheus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push grafana
        uses: docker/build-push-action@v4
        with:
          context: ./metrics/grafana
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-grafana:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push vector
        uses: docker/build-push-action@v4
        with:
          context: ./logs/vector
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-vector:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push elasticsearch
        uses: docker/build-push-action@v4
        with:
          context: ./logs/elasticsearch
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-elasticsearch:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push kibana
        uses: docker/build-push-action@v4
        with:
          context: ./logs/kibana
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-kibana:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push logstash
        uses: docker/build-push-action@v4
        with:
          context: ./logs/logstash
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-logstash:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      