name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push auth service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-auth:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push chat service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/chat
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-chat:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push game service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/game
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-game:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push dash service image
        uses: docker/build-push-action@v4
        with:
          context: ./services/dash
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-dash:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push redis
        uses: docker/build-push-action@v4
        with:
          context: ./infra/dockerfiles/Dockerfile.rd
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-redis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: ./infra/dockerfiles/Dockerfile.pg
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-postgres:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push kafka
        uses: docker/build-push-action@v4
        with:
          context: ./infra/dockerfiles/Dockerfile.kf
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-kafka:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push pgadmin
        uses: docker/build-push-action@v4
        with:
          context: ./infra/dockerfiles/Dockerfile.pga
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-pgadmin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push nginx
        uses: docker/build-push-action@v4
        with:
          context: ./infra/dockerfiles/Dockerfile.ng
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blackholejs-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      